name: gtc-converter
channels:
  - defaults
dependencies:
  # Pin to Python 3.10 so the stdlib still provides distutils (removed in 3.12+)
  - python=3.10
  - numpy
  - pip
  - setuptools
  - pip:
    - tensorflow
    # Pin tensorflowjs to 3.18.0 to avoid pulling tensorflow-decision-forests (which
    # currently builds from source on Windows and failed during install). The 3.x
    # series is compatible with tensorflow-hub<0.13.
    - "tensorflowjs==3.18.0"
    # tensorflowjs expects tensorflow-hub < 0.13; pin a compatible hub
    - "tensorflow-hub==0.12.0"