# =============================================================================
# GHOST TYPE CORRECTOR - GPU-ACCELERATED ENVIRONMENT
# =============================================================================
# This environment is optimized for NVIDIA GPU training with CUDA support.
# 
# Requirements:
#   - NVIDIA GPU with CUDA Compute Capability 3.5 or higher
#   - NVIDIA GPU drivers installed
#
# Installation:
#   conda env create -f environment-gpu.yml
#   conda activate ghost-corrector-gpu
#   
# Verify GPU:
#   python -c "import tensorflow as tf; print('GPUs:', tf.config.list_physical_devices('GPU'))"
#
# =============================================================================

name: ghost-corrector-gpu

channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # Core scientific computing
  - numpy=1.24.3
  - pandas
  - scipy
  - tqdm

  # Jupyter for development and visualization
  - jupyterlab
  - matplotlib
  - seaborn
  - ipywidgets

  # Data processing
  - h5py

  # Package manager
  - pip

  # Install via pip for precise version control
  - pip:
      # TensorFlow with GPU support
      # TensorFlow 2.10 is the last version with native Windows GPU support
      - tensorflow==2.10.1
      
      # TensorFlow.js converter
      - tensorflowjs==4.4.0
      
      # Additional utilities
      - protobuf<3.20
      
# =============================================================================
# POST-INSTALLATION STEPS (IMPORTANT!)
# =============================================================================
# After creating the environment, install CUDA Toolkit and cuDNN:
#
#   conda activate ghost-corrector-gpu
#   conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
#
# These specific versions are required for TensorFlow 2.10 GPU support.
# =============================================================================
