# =============================================================================
# GHOST TYPE CORRECTOR - CPU-ONLY ENVIRONMENT
# =============================================================================
# This environment is optimized for CPU-only training and inference.
# Universal compatibility - works on any system (Windows, macOS, Linux).
#
# Installation:
#   conda env create -f environment-cpu.yml
#   conda activate ghost-corrector-cpu
#
# Verify installation:
#   python -c "import tensorflow as tf; print('TensorFlow version:', tf.__version__)"
#
# =============================================================================

name: ghost-corrector-cpu

channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # Core scientific computing
  - numpy=1.24.3
  - pandas
  - scipy
  - tqdm

  # Jupyter for development and visualization
  - jupyterlab
  - matplotlib
  - seaborn
  - ipywidgets

  # Data processing
  - h5py

  # TensorFlow CPU-optimized version
  - tensorflow-cpu=2.10.0

  # Package manager
  - pip

  # Install via pip for precise version control
  - pip:
      # Additional utilities
      - protobuf<3.20
      
      # Note: tensorflowjs will be installed manually after environment creation
      # to avoid tensorflow-decision-forests dependency conflict

# =============================================================================
# USAGE NOTES
# =============================================================================
# This CPU-only environment is suitable for:
#   - Development and testing
#   - Inference on the trained model
#   - Training on smaller datasets (may be slower than GPU)
#
# For GPU-accelerated training, use environment-gpu.yml instead.
# =============================================================================
